version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: gradle
    directory: /back
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build"

  - package-ecosystem: npm
    directory: /front
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    commit-message:
      prefix: "build"
    groups:
      angular:
        patterns: ["@angular/*", "@angular-devkit/*", "@ngtools/*"]
        update-types: ["patch"]
    ignore:
      - dependency-name: "@angular/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "@angular-devkit/*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "zone.js"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]