sonar.projectKey=clems2_P7-CICD-Full-Stack_Front
sonar.organization=clems2
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/microcrm/lcov.info